version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: css-loader
    versions:
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: stylelint-config-standard
    versions:
    - 21.0.0
  - dependency-name: fullcalendar
    versions:
    - 5.5.1
  - dependency-name: cross-env
    versions:
    - 7.0.3
  - dependency-name: imagemin-webpack-plugin
    versions:
    - 2.4.2
  - dependency-name: html-webpack-plugin
    versions:
    - 3.2.0
  - dependency-name: file-loader
    versions:
    - 2.0.0
  - dependency-name: postcss-loader
    versions:
    - 3.0.0
  - dependency-name: style-loader
    versions:
    - 0.23.1
  - dependency-name: babel-eslint
    versions:
    - 10.1.0
  - dependency-name: sass-loader
    versions:
    - 7.3.1
